before_build:
- nuget restore
build:
  publish_wap: true
  verbosity: minimal
notifications:
- provider: Email
  to:
  - team@appveyor.com
  subject: 'Another notification - Build {{status}}: {{projectName}} {{buildVersion}}'
  on_build_success: true
  on_build_failure: true
